services:

  db:
    env_file: .env
    image: postgres:15-alpine
    container_name: listener-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DEV__DATABASE_PASSWORD}
      POSTGRES_USER: ${DEV__DATABASE_USER}
      POSTGRES_DB: ${DEV__DATABASE_NAME}
    ports:
      - "5432:5432"
